export const VERSION = '0.1.0';

export const PALETTE = {
  ink: 0x080a18,
  panel: 0x11162c,
  grid: 0x182040,
  cyan: 0x5df2ff,
  magenta: 0xff4fd8,
  lime: 0xa7ff4f,
  amber: 0xffc857,
  danger: 0xff365f,
  void: 0x4c22aa,
  white: 0xf4f7ff,
};

export const RUNNERS = {
  flux: {
    id: 'flux',
    name: 'FLUX',
    role: 'MOBILITY',
    color: PALETTE.cyan,
    accent: PALETTE.magenta,
    hp: 92,
    speed: 8.4,
    fireRate: 0.18,
    damage: 15,
    projectileSpeed: 22,
    dash: 8.5,
    description: 'Fast phase runner. Precise pulse carbine and the shortest dash recovery.',
    stats: [92, 96, 74],
  },
  nova: {
    id: 'nova',
    name: 'NOVA',
    role: 'DISRUPTION',
    color: PALETTE.magenta,
    accent: PALETTE.amber,
    hp: 108,
    speed: 7.3,
    fireRate: 0.3,
    damage: 24,
    projectileSpeed: 18,
    dash: 7,
    description: 'Heavy arc caster. Slower shots hit hard and overload relays quickly.',
    stats: [78, 70, 96],
  },
  rook: {
    id: 'rook',
    name: 'ROOK',
    role: 'CONTROL',
    color: PALETTE.lime,
    accent: PALETTE.cyan,
    hp: 126,
    speed: 6.6,
    fireRate: 0.24,
    damage: 18,
    projectileSpeed: 20,
    dash: 6.2,
    description: 'Armoured gridkeeper. Durable chassis with stable three-round pressure.',
    stats: [100, 62, 82],
  },
};

export const GAME = {
  arenaSize: 34,
  tileCount: 17,
  bots: 7,
  collapseStart: 28,
  collapseDuration: 82,
  maxMatchTime: 150,
  dashCooldown: 3.4,
  overdriveDuration: 5,
  relayFuse: 1.8,
};
